### ISSUE TITLE
As a user, I want to fill in my information, so that I can complete checkout and submit my order.

### ISSUE THREAD

**Issue by n0land0** [n0land0/audiophilia#10]
### Acceptance Criteria
Scenario: User is viewing checkout page
- Given: User wants to finalize their order
- When: User fills in fields in checkout form
- Then: User is able to submit the form to complete their order

### Wireframe
- Checkout

### Tasks
- [ ] Required fields warning
- [ ] Summary has editable quantity (?)
  - Summary as controlled form?
- [ ] 'Continue & pay' button launches confirmation dialog/modal
